"""
Internationalization (i18n) module for multi-language support
Supports: French (fr), English (en)
"""

import os
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)


class I18n:
    """Handles translations for the application"""
    
    # Translation dictionaries
    TRANSLATIONS = {
        'en': {
            # Email subjects and bodies
            'email_subject': '📊 Weekly Summary - Week of {start} to {end}',
            'email_greeting': 'Hello,',
            'email_intro': 'Here is your weekly summary for the week of {start} to {end}.',
            'email_footer': 'This summary was automatically generated by Todoist AI Summary.',
            'email_generated_at': 'Generated on {date}',
            
            # Log messages
            'log_startup': 'Starting Todoist AI Summary script',
            'log_period': 'Analysis period: {start} to {end}',
            'log_step': 'Step {step}/{total}: {action}...',
            'log_connecting_todoist': 'Connecting to Todoist',
            'log_tasks_found': '{count} completed tasks retrieved',
            'log_organizing_tasks': 'Organizing tasks',
            'log_generating_summary': 'Generating AI summary',
            'log_context_loaded': 'Context loaded: {count} previous weeks',
            'log_summary_generated': 'Summary generated successfully',
            'log_saving_local': 'Saving locally',
            'log_summary_saved': 'Summary saved locally',
            'log_sending_email': 'Sending email',
            'log_email_sent': 'Email sent successfully',
            'log_script_complete': 'Script completed successfully!',
            'log_no_tasks': 'No completed tasks this week. Stopping script.',
            'log_error': 'Error during execution',
            
            # Markdown labels
            'md_weekly_summary': 'Weekly Summary - Week of {start} to {end}',
            'md_generated_on': 'Generated on {date}',
            'md_summary_title': '📝 Summary',
            'md_stats_title': '📊 Statistics',
            'md_total_tasks': '**Total completed tasks**: {count}',
            'md_tasks_detail': '📋 Task Details',
            'md_category': '{category}',
            
            # Email categories (displayed in emails/markdown)
            'category_display_work': '💼 Work',
            'category_display_personal': '🏠 Personal',
            'category_display_tinker': '🔧 Tinker',
            'category_display_other': '📌 Other',
            
            # Prompt instructions for AI
            'prompt_system': 'You are an assistant that helps write personal weekly summaries in a factual and structured manner.',
            'prompt_period': 'PERIOD: Week of {start} to {end}',
            'prompt_context': 'CONTEXT (previous weeks):',
            'prompt_tasks': 'COMPLETED TASKS THIS WEEK:',
            'prompt_subproject': '[Subproject: {name}]',
            'prompt_instructions': 'INSTRUCTIONS',
            'prompt_instruction_text': 'Write a summary of my week based ONLY on the completed tasks above.',
            'prompt_format': 'REQUIRED FORMAT (MARKDOWN STRUCTURE):',
            'prompt_style': 'STYLE:',
            'prompt_style_rules': '''- Factual and professional but natural tone
- First person ("I...", "I focused on...")
- No bullet points, only fluid paragraphs in complete sentences
- DO NOT extrapolate emotions or feelings (example: avoid "that was annoying", "spent a lot of time", etc.)
- Stay strictly factual: describe what was done, not how I felt
- If you have context from previous weeks, ensure natural narrative continuity
- Use EXACTLY the titles ## and ### as indicated above''',
            'prompt_important': 'IMPORTANT:',
            'prompt_important_rules': '''- Use Markdown titles (##) for each main category
- Use subtitles (###) ONLY for subprojects that exist
- If a category has no subprojects (just a category name), write the paragraph directly without subtitle ###
- Each subproject must have its own distinct paragraph under its ### title
- Start directly with Markdown titles, no introduction''',
            'prompt_request': 'Now write the summary following EXACTLY this structure:',
        },
        'fr': {
            # Email subjects and bodies
            'email_subject': '📊 Résumé hebdomadaire - Semaine du {start} au {end}',
            'email_greeting': 'Bonjour,',
            'email_intro': 'Voici ton résumé hebdomadaire pour la semaine du {start} au {end}.',
            'email_footer': 'Ce résumé a été généré automatiquement par Todoist AI Summary.',
            'email_generated_at': 'Généré le {date}',
            
            # Log messages
            'log_startup': 'Démarrage du script Todoist AI Summary',
            'log_period': 'Période analysée : {start} au {end}',
            'log_step': 'Étape {step}/{total} : {action}...',
            'log_connecting_todoist': 'Connexion à Todoist',
            'log_tasks_found': '{count} tâches complétées récupérées',
            'log_organizing_tasks': 'Organisation des tâches',
            'log_generating_summary': 'Génération du résumé IA',
            'log_context_loaded': 'Contexte chargé : {count} semaines précédentes',
            'log_summary_generated': 'Résumé généré avec succès',
            'log_saving_local': 'Sauvegarde locale',
            'log_summary_saved': 'Résumé sauvegardé localement',
            'log_sending_email': 'Envoi par email',
            'log_email_sent': 'Email envoyé avec succès',
            'log_script_complete': 'Script terminé avec succès !',
            'log_no_tasks': 'Aucune tâche complétée cette semaine. Arrêt du script.',
            'log_error': 'Erreur lors de l\'exécution',
            
            # Markdown labels
            'md_weekly_summary': 'Résumé hebdomadaire - Semaine du {start} au {end}',
            'md_generated_on': 'Généré le {date}',
            'md_summary_title': '📝 Résumé',
            'md_stats_title': '📊 Statistiques',
            'md_total_tasks': '**Total de tâches complétées** : {count}',
            'md_tasks_detail': '📋 Détail des tâches',
            'md_category': '{category}',
            
            # Email categories (displayed in emails/markdown)
            'category_display_work': '💼 Travail',
            'category_display_personal': '🏠 Personnel',
            'category_display_tinker': '🔧 Tinker',
            'category_display_other': '📌 Autres',
            
            # Prompt instructions for AI
            'prompt_system': 'Tu es un assistant qui aide à rédiger des résumés hebdomadaires personnels de manière factuelle et structurée.',
            'prompt_period': 'PÉRIODE : Semaine du {start} au {end}',
            'prompt_context': 'CONTEXTE (semaines précédentes) :',
            'prompt_tasks': 'TÂCHES COMPLÉTÉES CETTE SEMAINE :',
            'prompt_subproject': '[Sous-projet: {name}]',
            'prompt_instructions': 'INSTRUCTIONS',
            'prompt_instruction_text': 'Rédige un résumé de ma semaine en te basant UNIQUEMENT sur les tâches complétées ci-dessus.',
            'prompt_format': 'FORMAT REQUIS (STRUCTURE MARKDOWN) :',
            'prompt_style': 'STYLE :',
            'prompt_style_rules': '''- Ton factuel et professionnel mais naturel
- À la 1ère personne ("J'ai...", "Je me suis concentré sur...")
- Pas de liste à puces, uniquement des paragraphes fluides en phrases complètes
- NE PAS extrapoler d'émotions ou de ressentis (exemple : éviter "qui m'agaçait", "pas mal de temps", etc.)
- Rester strictement factuel : décrire ce qui a été fait, pas comment je me suis senti
- Si tu as le contexte des semaines précédentes, assure une continuité narrative naturelle
- Utiliser EXACTEMENT les titres ## et ### comme indiqué ci-dessus''',
            'prompt_important': 'IMPORTANT :',
            'prompt_important_rules': '''- Utilise les titres Markdown (##) pour chaque catégorie principale
- Utilise les sous-titres (###) UNIQUEMENT pour les sous-projets qui existent
- Si une catégorie n'a pas de sous-projets (juste un nom de catégorie), écris directement le paragraphe sans sous-titre ###
- Chaque sous-projet doit avoir son propre paragraphe distinct sous son titre ###
- Commence directement par les titres Markdown, sans introduction''',
            'prompt_request': 'Rédige maintenant le résumé en suivant EXACTEMENT cette structure :',
        }
    }
    
    def __init__(self):
        """Initialize i18n with language from environment"""
        self.language = os.getenv('LANGUAGE', 'en').lower()
        
        # Validate language
        if self.language not in self.TRANSLATIONS:
            logger.warning(f"Language '{self.language}' not supported, falling back to 'en'")
            self.language = 'en'
        
        logger.info(f"Language set to: {self.language}")
    
    def t(self, key: str, **kwargs) -> str:
        """
        Translate a key with optional formatting
        
        Args:
            key: Translation key
            **kwargs: Format arguments for the translation string
        
        Returns:
            Translated and formatted string
        """
        translation = self.TRANSLATIONS.get(self.language, {}).get(key)
        
        if translation is None:
            # Fallback to English
            translation = self.TRANSLATIONS.get('en', {}).get(key)
            if translation is None:
                logger.warning(f"Translation key '{key}' not found")
                return key
        
        # Format the string if kwargs provided
        if kwargs:
            try:
                return translation.format(**kwargs)
            except KeyError as e:
                logger.error(f"Missing format argument for key '{key}': {e}")
                return translation
        
        return translation
    
    def get_category_display_name(self, category: str) -> str:
        """
        Get the display name for a category
        
        Args:
            category: Category prefix (Work, Perso, Tinker, etc.)
        
        Returns:
            Translated category display name
        """
        # Map category to translation key
        category_map = {
            os.getenv('WORK_PREFIX', 'Work'): 'category_display_work',
            os.getenv('PERSONAL_PREFIX', 'Perso'): 'category_display_personal',
            os.getenv('TINKER_PREFIX', 'Tinker'): 'category_display_tinker',
        }
        
        key = category_map.get(category, 'category_display_other')
        return self.t(key)


# Global instance
_i18n_instance = None

def get_i18n() -> I18n:
    """Get the global i18n instance (singleton pattern)"""
    global _i18n_instance
    if _i18n_instance is None:
        _i18n_instance = I18n()
    return _i18n_instance